# Generated by Django 5.0.4 on 2024-05-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reg",
            fields=[
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=15)),
                ("dob", models.CharField(max_length=20)),
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=30)),
                ("cpassword", models.CharField(max_length=30)),
            ],
        ),
    ]
